# -*- coding: utf-8 -*-
"""final_mausoleum_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jR6pBdVsm6zoTiWNVIeuAu8fUPUXQPPX
"""

"""
NFT Death Score Analyzer
================================
Scores NFT collections across five active categories to assess whether a
collection is dead, dying, or recoverable.

Scoring architecture
--------------------
Each metric fires (triggers) when a collection shows a specific distress
signal. Triggered metrics contribute points to a raw score. The raw score
is then rescaled against the realistic maximum of scoreable points (22),
rather than the theoretical ceiling (19), to account for metrics that
chronically skip due to missing market data.

Active metric categories:
  Liquidity       — trading activity and volume signals
  Financial       — bid market health signals
  Social          — Twitter/Discord community signals
  Technical       — on-chain metadata integrity
  Ownership       — token concentration signals

Removed metrics (never fired across 233-collection dataset, v11):
  liq_unique_buyers_lt20pct_30d       — skipped 100%: no live 30d sales
  fin_median_bid_lt30pct_floor        — skipped 100%: no floor on dead collections
  inv_gt30pct_listings_near_floor     — skipped 75%, never triggered otherwise
  bot_wash_trading_gt40pct            — never triggered: wash detection needs
                                        active trading which dead collections lack
  own_gt50pct_trades_top_holders      — skipped 100%: no 30d trades to analyse

Verdict thresholds (applied to rescaled score out of 22):
  DEAD                  ≥ 11  (or ≥ 16 even with insufficient data)
  Decaying   7–10
  Stressed / Declining  4–6
  Alive or Recoverable  0–3
  Data Insufficient     < 8 of 10 metrics have data AND rescaled < 16

APIs used:
  OKX NFT Marketplace API   floor price, bids, asks, trade history
  OpenSea API v2             fallback when OKX has no market data
  Alchemy NFT API            ownership data and metadata validation
  Apify Tweet Scraper        Twitter engagement and recency
  Discord Public API         server existence and member count
"""

from google.colab import userdata
import os, csv, json, time, random, argparse, logging, hmac, hashlib, base64, re
from datetime import datetime, timedelta, timezone
from collections import defaultdict

import requests
import pandas as pd
from dotenv import load_dotenv
from tqdm import tqdm

# ── Environment setup ─────────────────────────────────────────────────────────

load_dotenv()

ALCHEMY_API_KEY    = userdata.get('ALCHEMY').strip()
OKX_API_KEY        = userdata.get('OKX_API_KEY').strip()
OKX_API_SECRET     = userdata.get('OKX_API_SECRET').strip()
OKX_API_PASSPHRASE = userdata.get('OKX_API_PASSPHRASE').strip()
OKX_PROJECT_ID     = userdata.get('OKX_PROJECT_ID').strip()
APIFY_API_TOKEN    = userdata.get('APIFY_API_TOKEN').strip()
OPENSEA_API_KEY    = userdata.get('OPENSEA_API_KEY').strip()

os.environ["ALCHEMY_API_KEY"]    = ALCHEMY_API_KEY
os.environ["OKX_API_KEY"]        = OKX_API_KEY
os.environ["OKX_API_SECRET"]     = OKX_API_SECRET
os.environ["OKX_API_PASSPHRASE"] = OKX_API_PASSPHRASE
os.environ["OKX_PROJECT_ID"]     = OKX_PROJECT_ID
os.environ["APIFY_API_TOKEN"]    = APIFY_API_TOKEN
os.environ["OPENSEA_API_KEY"]    = OPENSEA_API_KEY

APIFY_BASE = "https://api.apify.com/v2"

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
log = logging.getLogger(__name__)

# ── Tuning constants ──────────────────────────────────────────────────────────

# Metadata sampling: 1000 tokens sampled across 10 evenly-spaced bands of the
# token ID range, to avoid bias toward low or high token IDs.
METADATA_SAMPLE_SIZE     = 1000
METADATA_BANDS           = 10

# Alchemy's getOwnersForContract returns ~100 owners per page.
# We paginate up to this many pages to get complete ownership data for
# large collections (supply 30k–100k+).
ALCHEMY_OWNERS_MAX_PAGES = 50

# Twitter engagement: minimum tweets needed before the engagement metric
# can fire. Fewer than this and the metric is skipped to avoid noise.
ENGAGEMENT_COLLAPSE_THRESHOLD = 5.0
MIN_TWEETS_FOR_ENGAGEMENT     = 2

# OKX chain identifier for Ethereum mainnet.
OKX_ETH_CHAIN = "ethereum"

# Scoring thresholds (all applied to the rescaled score out of RESCALE_NORM).
RESCALE_NORM                    = 22   # output scale for rescaling; set slightly above TOTAL_MAX_PTS to preserve score spread when metrics skip on dead collections
TOTAL_MAX_PTS                   = None  # set after METRICS defined below
DI_DEAD_OVERRIDE                = 16   # score above this = DEAD regardless of data gaps
DATA_INSUFFICIENT_METRIC_THRESHOLD = 8  # fewer than this many metrics with data = DI flag

# ── Metric registry ───────────────────────────────────────────────────────────
# Each entry: (metric_key, max_points, category, human_label)
# Removing a metric here automatically removes it from all downstream logic.

METRICS = [
    ("liq_volume_30d_lt1pct_floor_value",      2, "Liquidity",  "30d Organic Volume < 1% of Floor Value"),
    ("liq_lt1_trade_per_day_60d",              2, "Liquidity",  "< 1 Trade/Day for 60 Consecutive Days"),
    ("fin_active_bids_lt1pct_supply",          2, "Financial",  "Active Bids < 1% of Supply"),
    ("fin_top10_bid_value_lt1pct_floor_value", 1, "Financial",  "Top-10 Bid ETH Value < 1% of Floor Value"),
    ("soc_twitter_silent_120d",                3, "Social",     "No Twitter Post in 120+ Days"),
    ("soc_discord_dead",                       2, "Social",     "Discord Server Deleted (2 pts) or <100 Members (1 pt)"),
    ("soc_engagement_collapse",                2, "Social",     "Avg Engagement/Tweet < 5 (likes+RTs+replies, last 5 tweets)"),
    ("tech_broken_metadata_gt50pct",           3, "Technical",  ">50% Tokens Have Broken Metadata/Images"),
    ("inv_gt20pct_supply_listed",              1, "Inventory",  ">20% of Supply Listed for Sale"),
    ("own_top10_wallets_gt50pct_supply",       1, "Ownership",  "Top-10 Wallets Hold >50% of Supply"),
]

METRIC_PREFIXES = [m[0] for m in METRICS]
METRIC_LABELS   = {m[0]: m[3] for m in METRICS}
METRIC_MAX_PTS  = {m[0]: m[1] for m in METRICS}
METRIC_CATEGORY = {m[0]: m[2] for m in METRICS}
TOTAL_MAX_PTS   = sum(m[1] for m in METRICS)   # 19 pts theoretical ceiling

""""
Important note!

Originally, the theoretical ceiling was set to 20 points because the soc_discord_dead metric was registered for 3 points, while the underlying logic only allowed for a maximum of 2.
Consequently, the rescaled scores for each NFT are slightly deflated.
However, because this deflation was applied uniformly across the entire dataset, the relative ranking and final classifications remain robust.
The other distress signals are so severe in these collections that they meet the "dead" threshold even with this mathematical conservative bias.

"""


# ── Generic HTTP helpers ──────────────────────────────────────────────────────

def _get(url, params=None, headers=None, retries=3, timeout=20):
    """
    GET request with retry logic and rate-limit handling.
    Returns parsed JSON dict, or {} on failure.
    404s are returned immediately without retrying — they are definitive.
    429s trigger exponential backoff before retrying.
    """
    for attempt in range(retries):
        try:
            r = requests.get(url, params=params, headers=headers, timeout=timeout)
            if r.status_code == 429:
                wait = 2 ** attempt
                log.warning("Rate-limited – sleeping %ss", wait)
                time.sleep(wait)
                continue
            if r.status_code == 404:
                return {}   # definitive not-found, no value in retrying
            r.raise_for_status()
            return r.json()
        except Exception as exc:
            log.warning("Attempt %s/%s failed (%s): %s", attempt + 1, retries, url, exc)
            time.sleep(1)
    return {}


def _days_ago_ts(n: int) -> int:
    """Returns a Unix timestamp for n days ago (UTC), used as API cutoff filters."""
    return int((datetime.now(timezone.utc) - timedelta(days=n)).timestamp())


def _sale_age_days(sale: dict) -> float:
    """
    Returns how many days ago a sale occurred.
    Handles both millisecond and second timestamps.
    Returns 999.0 when no timestamp is present (treated as very old).
    """
    ts = sale.get("timestamp") or sale.get("tradeTime") or 0
    if ts:
        return (datetime.now(timezone.utc) -
                datetime.fromtimestamp(int(ts) / 1000 if int(ts) > 1e10 else int(ts),
                                       tz=timezone.utc)).total_seconds() / 86400
    return 999.0


def _verdict(score: int, metrics_with_data: int = 10) -> str:
    """
    Converts a rescaled score into a human-readable verdict.

    Logic:
      1. If score >= DI_DEAD_OVERRIDE (16), call it DEAD regardless of data
         coverage — the signal is too strong to be explained by missing data.
      2. If fewer than DATA_INSUFFICIENT_METRIC_THRESHOLD metrics have data,
         flag as Data Insufficient with the partial score shown for reference.
      3. Otherwise apply standard band thresholds.
    """
    if score >= DI_DEAD_OVERRIDE:
        return "DEAD"
    if metrics_with_data < DATA_INSUFFICIENT_METRIC_THRESHOLD:
        return f"Data Insufficient (partial score: {score})"
    if score >= 11: return "DEAD"
    if score >= 7:  return "Decaying"
    if score >= 4:  return "Stressed / Declining"
    return "Alive or Recoverable"


def _is_skipped(metric: dict) -> bool:
    """
    Returns True when a metric was skipped due to missing data.
    Skipped metrics are excluded from max_available so they don't
    artificially inflate or deflate the rescaled score.
    """
    detail = metric.get("detail", "").lower()
    return any(w in detail for w in (
        "skipped", "missing", "not_provided", "no_api_key",
        "no_handle", "insufficient", "no_supply", "no_floor",
        "no_asks", "no_ownership", "no_data", "no_sales",
        "no_bids", "no_okx", "no_twitter", "no_discord",
        "fetch_failed",
    ))


def _rate(value: float, high_thresh: float, low_thresh: float) -> str:
    """Maps a numeric value to HIGH / MEDIUM / LOW confidence tier."""
    if value >= high_thresh: return "HIGH"
    if value >= low_thresh:  return "MEDIUM"
    return "LOW"


def _rescale(raw_score: int, max_available: int) -> int:
    """
    Normalises raw_score against the points that were actually scoreable
    (max_available), then scales to RESCALE_NORM (22).

    This prevents dead collections from appearing artificially healthy just
    because many metrics had to be skipped due to missing market data.
    A collection that scores 8/10 available points rescales to ~18/22,
    not 8/20.
    """
    if max_available <= 0:
        return 0
    return round((raw_score / max_available) * RESCALE_NORM)


# ── OKX Authentication ────────────────────────────────────────────────────────

def _okx_headers(method: str, path: str, body: str = "") -> dict:
    """
    Builds OKX API authentication headers using HMAC-SHA256 signing.
    OKX requires a timestamp, signature, and passphrase on every request.
    """
    ts = datetime.now(timezone.utc).isoformat(timespec='milliseconds').replace('+00:00', 'Z')
    prehash = ts + method.upper() + path + body
    sig = base64.b64encode(
        hmac.new(OKX_API_SECRET.encode('utf-8'),
                 prehash.encode('utf-8'),
                 hashlib.sha256).digest()
    ).decode()
    return {
        "OK-ACCESS-KEY":        OKX_API_KEY,
        "OK-ACCESS-SIGN":       sig,
        "OK-ACCESS-TIMESTAMP":  ts,
        "OK-ACCESS-PASSPHRASE": OKX_API_PASSPHRASE,
        "OK-ACCESS-PROJECT":    OKX_PROJECT_ID,
        "Content-Type":         "application/json",
    }


def _okx_get(path: str, params: dict = None) -> dict:
    """
    Authenticated GET request to the OKX NFT API.
    Builds the signed URL, calls _get(), and validates the OKX response code.
    Returns {} when credentials are missing or the API returns an error.
    """
    if not all([OKX_API_KEY, OKX_API_SECRET, OKX_API_PASSPHRASE, OKX_PROJECT_ID]):
        log.warning("OKX credentials incomplete — skipping request to %s", path)
        return {}
    query = ""
    if params:
        query = "?" + "&".join(f"{k}={v}" for k, v in sorted(params.items()))
    headers = _okx_headers("GET", path + query)
    data    = _get(f"https://web3.okx.com{path}{query}", params=None, headers=headers)
    if isinstance(data, dict):
        if data.get("code") == 0:
            return data
        if data:
            log.warning("OKX non-zero response: code=%s msg=%s",
                        data.get("code"), data.get("msg", ""))
    return {}


# ── OKX NFT Client ────────────────────────────────────────────────────────────

class OKXClient:
    """
    Fetches NFT collection data from the OKX marketplace API.

    OKX uses its own internal slug system that bears no relation to OpenSea
    slugs. collection_details() uses five successive strategies to resolve
    a slug before giving up, falling back to partial asset-level data.
    """

    def collection_details(self, contract: str, slug: str = "",
                           opensea_link: str = "",
                           collection_name: str = "") -> dict:
        """
        Resolves a collection slug and fetches full detail from OKX.

        Resolution strategies (tried in order, first success wins):
          1. OKX asset endpoint      — pulls slug from a single token response
          2. Parse opensea_link      — extracts slug from /collection/<slug> URLs
          3. OKX contract search     — searches OKX by contract address
          4. OKX keyword search      — searches OKX by collection display name
          5. Caller-supplied slug    — normalised to lowercase-hyphen

        Falls back to partial asset-level data (supply available but no
        floor/stats) if all strategies fail to reach the detail endpoint.
        """
        contract      = contract.lower().strip()
        clean_slug    = str(slug).strip()
        okx_slug      = ""
        fallback_data = {}

        # Strategy 1: pull slug from a token-level asset response
        asset_data = _okx_get("/api/v5/mktplace/nft/asset/list", {
            "chain": OKX_ETH_CHAIN, "contractAddress": contract, "limit": "1",
        })
        items = asset_data.get("data", [])
        if isinstance(items, dict):
            items = items.get("data", [])
        if items and isinstance(items, list) and items[0]:
            col_obj       = items[0].get("collection", {})
            okx_slug      = col_obj.get("slug", "")
            fallback_data = col_obj
            if okx_slug:
                log.info("OKX slug from asset endpoint: %s", okx_slug)

        # Strategy 2: extract from opensea_link if it contains /collection/<slug>
        if not okx_slug:
            link = str(opensea_link).strip()
            if "/collection/" in link:
                os_slug = link.rstrip("/").split("/collection/")[-1].split("/")[0]
                if os_slug and os_slug.lower() not in ("", "nan", "none"):
                    okx_slug = os_slug
                    log.info("OKX slug from opensea_link: %s", okx_slug)

        # Strategy 3: OKX contract address search
        if not okx_slug:
            search_data = _okx_get("/api/v5/mktplace/nft/collection/search", {
                "chain": OKX_ETH_CHAIN, "contractAddress": contract, "limit": "1",
            })
            s_items = search_data.get("data", [])
            if isinstance(s_items, dict):
                s_items = s_items.get("data", [])
            if isinstance(s_items, list) and s_items:
                okx_slug = s_items[0].get("slug", "")
                if okx_slug:
                    log.info("OKX slug from contract search: %s", okx_slug)

        # Strategy 4: OKX keyword search by collection display name.
        # Strips common suffixes (NFT, Official, Collection) that differ
        # between platforms, then matches by contractAddress in results.
        if not okx_slug and collection_name and \
                str(collection_name).lower() not in ("", "nan", "none"):
            keyword = re.sub(r'\s+(nft|official|collection)s?$', '',
                             collection_name.strip(), flags=re.IGNORECASE)
            kw_data = _okx_get("/api/v5/mktplace/nft/collection/search", {
                "chain": OKX_ETH_CHAIN, "keyword": keyword[:50], "limit": "5",
            })
            k_items = kw_data.get("data", [])
            if isinstance(k_items, dict):
                k_items = k_items.get("data", [])
            if isinstance(k_items, list) and k_items:
                matched = next(
                    (x for x in k_items
                     if (x.get("contractAddress") or "").lower() == contract),
                    k_items[0]
                )
                okx_slug = matched.get("slug", "")
                if okx_slug:
                    log.info("OKX slug from keyword search (%r): %s", keyword, okx_slug)

        # Strategy 5: normalise and use the caller-supplied slug directly
        if not okx_slug and clean_slug and clean_slug.lower() not in ("nan", "none", ""):
            okx_slug = clean_slug.lower().replace(" ", "-")
            log.info("OKX slug from caller-supplied value: %s", okx_slug)

        # Fetch full collection detail using the resolved slug
        if okx_slug:
            detail_data = _okx_get("/api/v5/mktplace/nft/collection/detail",
                                   {"slug": okx_slug})
            d_items = detail_data.get("data", [])
            if isinstance(d_items, dict):
                d_items = [d_items]
            if isinstance(d_items, list) and d_items:
                res   = d_items[0]
                stats = res.get("stats", {})
                if isinstance(stats, dict):
                    res.update(stats)
                if res:
                    return res

        if fallback_data:
            return fallback_data

        log.warning("OKX: no collection data for %s (tried slug=%s)", contract[:12], okx_slug)
        return {}

    @staticmethod
    def collection_image(details: dict) -> str:
        """Extracts the best available image URL from OKX collection details."""
        return (
            details.get("image") or details.get("logoUrl") or
            details.get("backgroundImage") or details.get("coverUrl") or
            details.get("bannerUrl") or ""
        )

    @staticmethod
    def floor_price_eth(details: dict, asks: list = None, trades: list = None) -> float:
        """
        Returns the floor price in ETH using a three-tier fallback chain:
          Tier 1 — OKX detail floorPrice field (most reliable)
          Tier 2 — Lowest active ask price (when floor field is missing)
          Tier 3 — Most recent trade price (last resort for dead collections)

        Without this fallback, liq_volume, fin_bid_depth, and inv_near_floor
        all skip on collections where OKX returns floor=0.
        """
        try:
            fp = float(details.get("floorPrice") or 0)
            if fp > 0:
                return fp
        except Exception:
            pass

        if asks:
            prices = [float(a.get("price", 0) or a.get("unitPrice", 0) or 0)
                      for a in asks]
            prices = [p for p in prices if p > 0]
            if prices:
                floor = min(prices)
                log.info("Floor proxied from lowest ask: %.6f ETH", floor)
                return floor

        if trades:
            for t in sorted(trades,
                            key=lambda x: int(x.get("dealTime") or x.get("tradeTime") or 0),
                            reverse=True):
                try:
                    p = float(t.get("dealPrice") or t.get("price") or 0)
                    if p > 0:
                        log.info("Floor proxied from recent trade: %.6f ETH", p)
                        return p
                except Exception:
                    pass

        return 0.0

    @staticmethod
    def supply(details: dict) -> int:
        """Returns total token supply from OKX collection details."""
        try:
            return int(details.get("totalSupply") or details.get("totalCount") or 0)
        except Exception:
            return 0

    def active_listings(self, contract: str, limit: int = 2000) -> list:
        """
        Fetches all active listings (asks) for a collection, paginating
        through cursor-based pages until the limit is reached or no more
        results are returned.
        """
        path, items, cursor = "/api/v5/mktplace/nft/markets/listings", [], None
        while len(items) < limit:
            params = {"chain": OKX_ETH_CHAIN,
                      "collectionAddress": contract.lower().strip(), "limit": "50"}
            if cursor:
                params["cursor"] = cursor
            data  = _okx_get(path, params)
            inner = data.get("data", {})
            batch = inner.get("data", []) if isinstance(inner, dict) else inner
            if not batch:
                break
            items.extend(batch)
            cursor = inner.get("cursor") if isinstance(inner, dict) else None
            if not cursor:
                break
        return items

    def active_bids(self, contract: str, limit: int = 500) -> list:
        """
        Fetches all active bids (offers) for a collection, paginating
        through cursor-based pages until the limit is reached.
        """
        path, items, cursor = "/api/v5/mktplace/nft/markets/offers", [], None
        while len(items) < limit:
            params = {"chain": OKX_ETH_CHAIN,
                      "collectionAddress": contract.lower().strip(), "limit": "50"}
            if cursor:
                params["cursor"] = cursor
            data  = _okx_get(path, params)
            inner = data.get("data", {})
            batch = inner.get("data", []) if isinstance(inner, dict) else inner
            if not batch:
                break
            items.extend(batch)
            cursor = inner.get("cursor") if isinstance(inner, dict) else None
            if not cursor:
                break
        return items

    def trade_history(self, contract: str, days: int = 90) -> list:
        """
        Fetches trade history for the past `days` days, stopping as soon
        as trades older than the cutoff are encountered.
        """
        path      = "/api/v5/mktplace/nft/markets/trades"
        items     = []
        cursor    = None
        cutoff_ms = _days_ago_ts(days) * 1000
        while True:
            params = {"chain": OKX_ETH_CHAIN,
                      "collectionAddress": contract.lower().strip(), "limit": "50"}
            if cursor:
                params["cursor"] = cursor
            data  = _okx_get(path, params)
            inner = data.get("data", {})
            batch = inner.get("data", []) if isinstance(inner, dict) else (inner or [])
            if not batch:
                break
            filtered, stop = [], False
            for t in batch:
                ts = int(t.get("dealTime") or t.get("tradeTime") or 0)
                if ts >= cutoff_ms:
                    filtered.append(t)
                else:
                    stop = True
                    break
            items.extend(filtered)
            cursor = inner.get("cursor") if isinstance(inner, dict) else None
            if stop or not cursor:
                break
        return items

    def daily_volume_proxy(self, trades_90: list) -> list:
        """
        Aggregates trade history into a per-day volume and sales-count
        structure covering the last 91 days. Day 0 = today, day 90 = 90
        days ago. Used by the trade frequency and volume metrics.
        """
        today  = datetime.now(timezone.utc).date()
        by_day = defaultdict(lambda: {"volume": 0.0, "sales_count": 0})
        for t in trades_90:
            ts = int(t.get("dealTime") or t.get("tradeTime") or 0)
            if ts == 0:
                continue
            if ts > 1e10:
                ts = ts / 1000
            day_index = (today - datetime.fromtimestamp(ts, tz=timezone.utc).date()).days
            price     = float(t.get("dealPrice") or t.get("price") or 0)
            by_day[day_index]["volume"]      += price
            by_day[day_index]["sales_count"] += 1
        return [{"day_index": i, **by_day[i]} for i in range(91)]


# ── Alchemy Client ────────────────────────────────────────────────────────────

class AlchemyClient:
    """
    Fetches NFT ownership and metadata from Alchemy's NFT API v3.
    Used for ownership concentration scoring and metadata integrity checks.
    """

    def __init__(self, api_key: str):
        self.base = f"https://eth-mainnet.g.alchemy.com/nft/v3/{api_key}"

    def owners(self, contract: str) -> list:
        """
        Returns the full list of token owners for a contract, paginating
        through all pages via the pageKey cursor.

        Alchemy returns ~100 owners per page. Without pagination, large
        collections (30k–100k+ tokens) would appear to have no top-holder
        concentration because only the first 100 owners were visible.
        """
        all_owners, page_key = [], None
        for page_num in range(ALCHEMY_OWNERS_MAX_PAGES):
            params = {"contractAddress": contract, "withTokenBalances": True}
            if page_key:
                params["pageKey"] = page_key
            data     = _get(f"{self.base}/getOwnersForContract", params=params)
            batch    = data.get("owners", [])
            all_owners.extend(batch)
            page_key = data.get("pageKey")
            if not page_key:
                break
            if page_num % 10 == 9:
                log.info("Alchemy owners: fetched %d so far (page %d)…",
                         len(all_owners), page_num + 1)
        log.info("Alchemy owners: total=%d for %s", len(all_owners), contract[:12])
        return all_owners

    def token_metadata_batch(self, contract: str, token_ids: list) -> list:
        """
        Fetches NFT metadata for a list of token IDs in batches of 50
        (Alchemy's batch limit). Used to detect broken metadata/images.

        Returns a list of NFT metadata dicts. On 500 errors, the batch is
        skipped and an empty list is returned for that chunk.
        """
        results = []
        for i in range(0, len(token_ids), 50):
            chunk   = token_ids[i:i + 50]
            payload = {"tokens": [{"contractAddress": contract, "tokenId": str(t)}
                                   for t in chunk]}
            try:
                r = requests.post(f"{self.base}/getNFTMetadataBatch",
                                  json=payload, timeout=30)
                r.raise_for_status()
                results.extend(r.json().get("nfts", []))
            except Exception as exc:
                log.warning("Alchemy metadata batch error: %s", exc)
        return results


# ── OpenSea Fallback Client ───────────────────────────────────────────────────

class OpenSeaClient:
    """
    Fallback market data source when OKX has no data for a collection.

    Activated when OKX returns floor=0, zero trades, and zero asks.
    Provides floor price, listings, offers, and trade events in a format
    normalised to match OKX's data structure so all downstream metric
    functions work without modification.

    Requires OPENSEA_API_KEY (free tier sufficient).
    All methods return empty structures gracefully when key is absent.
    """

    BASE    = "https://api.opensea.io/api/v2"
    HEADERS = {"accept": "application/json", "x-api-key": OPENSEA_API_KEY}

    def _os_get(self, path: str, params: dict = None) -> dict:
        """Authenticated GET to OpenSea API v2 with rate-limit retry."""
        if not OPENSEA_API_KEY:
            return {}
        url = f"{self.BASE}{path}"
        for attempt in range(3):
            try:
                r = requests.get(url, params=params, headers=self.HEADERS, timeout=20)
                if r.status_code == 429:
                    time.sleep(2 ** attempt)
                    continue
                if r.status_code == 404:
                    return {}
                r.raise_for_status()
                return r.json()
            except Exception as exc:
                log.warning("OpenSea attempt %d failed (%s): %s", attempt + 1, url, exc)
                time.sleep(1)
        return {}

    def resolve_slug(self, contract: str) -> str:
        """
        Resolves a contract address to its OpenSea collection slug.

        Uses two strategies:
          1. /asset_contract/{address} — direct contract lookup
          2. /collections?asset_contract_address= — search fallback

        Handles the OpenSea v2 quirk where 'collection' can be either a
        plain string slug or a nested dict containing the slug.
        """
        data = self._os_get(f"/asset_contract/{contract.lower()}")

        def _extract(d: dict) -> str:
            col = d.get("collection") or d.get("slug") or ""
            if isinstance(col, dict):
                col = col.get("slug") or col.get("collection") or ""
            col = str(col).strip()
            return col if col.lower() not in ("", "nan", "none") else ""

        slug = _extract(data)
        if not slug:
            data2   = self._os_get("/collections",
                                   {"asset_contract_address": contract.lower(), "limit": "1"})
            results = data2.get("collections", [])
            if results:
                slug = _extract(results[0]) or str(results[0].get("slug", "")).strip()

        if slug:
            log.info("OpenSea slug for %s: %s", contract[:12], slug)
        else:
            log.info("OpenSea: no slug found for %s", contract[:12])
        return slug

    def floor_price_eth(self, slug: str) -> float:
        """Returns the OpenSea floor price in ETH for a collection slug."""
        if not slug:
            return 0.0
        stats = self._os_get(f"/collections/{slug}/stats") or {}
        try:
            fp = float(stats.get("total", {}).get("floor_price", 0) or
                       stats.get("floor_price", 0) or 0)
            if fp > 0:
                log.info("OpenSea floor for %s: %.6f ETH", slug, fp)
            return fp
        except Exception:
            return 0.0

    def active_listings(self, slug: str, limit: int = 200) -> list:
        """
        Fetches active listings from OpenSea and normalises them to
        OKX-style dicts (price, unitPrice fields) for metric compatibility.
        """
        if not slug:
            return []
        items, next_cur = [], None
        while len(items) < limit:
            params = {"limit": min(50, limit - len(items))}
            if next_cur:
                params["next"] = next_cur
            data  = self._os_get(f"/listings/collection/{slug}/best", params)
            batch = data.get("listings", [])
            if not batch:
                break
            for lst in batch:
                price_obj = (lst.get("price") or {}).get("current", {})
                try:
                    val = float(price_obj.get("value", 0) or 0)
                    dec = int(price_obj.get("decimals", 18) or 18)
                    eth = val / (10 ** dec)
                except Exception:
                    eth = 0.0
                items.append({"price": eth, "unitPrice": eth, "source": "opensea"})
            next_cur = data.get("next")
            if not next_cur:
                break
        return items

    def active_offers(self, slug: str, limit: int = 200) -> list:
        """
        Fetches collection-level offers (bids) from OpenSea and normalises
        them to OKX-style dicts for metric compatibility.
        """
        if not slug:
            return []
        items, next_cur = [], None
        while len(items) < limit:
            params = {"limit": min(50, limit - len(items))}
            if next_cur:
                params["next"] = next_cur
            data  = self._os_get(f"/offers/collection/{slug}/best", params)
            batch = data.get("offers", [])
            if not batch:
                break
            for off in batch:
                price_obj = (off.get("price") or {}).get("current", {})
                try:
                    val = float(price_obj.get("value", 0) or 0)
                    dec = int(price_obj.get("decimals", 18) or 18)
                    eth = val / (10 ** dec)
                except Exception:
                    eth = 0.0
                items.append({"price": eth, "unitPrice": eth, "source": "opensea"})
            next_cur = data.get("next")
            if not next_cur:
                break
        return items

    def trade_events(self, slug: str, days: int = 90, limit: int = 300) -> list:
        """
        Fetches sale events from OpenSea and normalises them to OKX-style
        trade dicts (dealTime, dealPrice, buyer/seller address fields).
        Stops fetching once events older than `days` are encountered.
        """
        if not slug:
            return []
        items, next_cur, cutoff = [], None, _days_ago_ts(days)
        while len(items) < limit:
            params = {"event_type": "sale", "limit": min(50, limit - len(items))}
            if next_cur:
                params["next"] = next_cur
            data  = self._os_get(f"/events/collection/{slug}", params)
            batch = data.get("asset_events", [])
            if not batch:
                break
            stop = False
            for ev in batch:
                ts = int(ev.get("event_timestamp", 0) or 0)
                if ts < cutoff:
                    stop = True
                    break
                price_obj = ev.get("payment", {})
                try:
                    val = float(price_obj.get("quantity", 0) or 0)
                    dec = int(price_obj.get("decimals", 18) or 18)
                    eth = val / (10 ** dec)
                except Exception:
                    eth = 0.0
                items.append({
                    "dealTime": ts * 1000, "tradeTime": ts * 1000,
                    "dealPrice": eth, "price": eth,
                    "buyer": (ev.get("buyer") or ""),
                    "buyerAddress": (ev.get("buyer") or ""),
                    "seller": (ev.get("seller") or ""),
                    "sellerAddress": (ev.get("seller") or ""),
                    "nftId": str((ev.get("nft") or {}).get("identifier", "")),
                    "source": "opensea",
                })
            next_cur = data.get("next")
            if stop or not next_cur:
                break
        return items


# ── Apify Twitter Client ──────────────────────────────────────────────────────

class TwitterStats:
    """Container for scraped Twitter metrics for a single account."""
    def __init__(self):
        self.days_since_last_post: float | None = None
        self.tweet_count:          int           = 0
        self.total_likes:          int           = 0
        self.total_retweets:       int           = 0
        self.total_replies:        int           = 0
        self.engagement_per_tweet: float         = 0.0


class ApifyTwitterClient:
    """
    Fetches recent tweet data via the Apify Tweet Scraper actor.

    A single Apify run per collection feeds both the silence metric
    (days since last post) and the engagement metric (likes+RTs+replies
    per tweet), avoiding double API costs.

    Date parsing handles multiple formats returned by different versions
    of the Apify actor and the underlying Twitter API. When all parse
    strategies fail (e.g. suspended/deleted account returning no date),
    days_since_last_post defaults to 999 so the silence metric fires
    conservatively rather than being skipped.
    """

    ACTOR_ID = "apidojo~tweet-scraper"

    _DATE_FORMATS = [
        "%a %b %d %H:%M:%S %z %Y",   # Twitter legacy: "Mon Apr 01 12:00:00 +0000 2024"
        "%Y-%m-%dT%H:%M:%S.%fZ",      # ISO with ms:    "2024-04-01T12:00:00.000Z"
        "%Y-%m-%dT%H:%M:%SZ",         # ISO no ms:      "2024-04-01T12:00:00Z"
        "%Y-%m-%d",                    # Date only:      "2024-04-01"
    ]

    def fetch_tweet_stats(self, handle: str) -> "TwitterStats | None":
        """
        Fetches the 5 most recent tweets for a handle and returns a
        TwitterStats object with silence days and engagement metrics.

        Returns None when no handle is provided or no Apify token is set.
        Returns stats with days_since_last_post=999.0 when the account
        exists but returns no tweets (suspended/empty accounts).
        """
        if not handle or not APIFY_API_TOKEN:
            return None

        handle = handle.lstrip("@").strip()
        if not handle:
            return None

        actor_input = {
            "startUrls": [{"url": f"https://twitter.com/{handle}"}],
            "maxItems":  5,
            "addUserInfo": False,
        }
        url = (f"{APIFY_BASE}/acts/{self.ACTOR_ID}"
               f"/run-sync-get-dataset-items"
               f"?token={APIFY_API_TOKEN}&timeout=60&maxItems=5")

        try:
            r = requests.post(url, json=actor_input, timeout=90)
            if r.status_code == 400:
                log.warning("Apify actor bad request for @%s: %s", handle, r.text[:200])
                return None
            r.raise_for_status()
            tweets = r.json()
        except Exception as exc:
            log.warning("Apify request failed for @%s: %s", handle, exc)
            return None

        # Empty tweet list = account exists but has no accessible tweets
        if not tweets:
            stats = TwitterStats()
            stats.days_since_last_post = 999.0
            return stats

        # Retweets are excluded — we measure the project's own voice only
        originals = [t for t in tweets
                     if not t.get("isRetweet") and not t.get("retweetedTweet")]
        if not originals:
            originals = tweets

        stats             = TwitterStats()
        stats.tweet_count = len(originals)

        # Parse the date of the most recent tweet using multiple strategies
        latest     = originals[0]
        created_at = (latest.get("createdAt") or latest.get("created_at") or
                      latest.get("date") or latest.get("timestamp") or "")

        parsed_dt = None

        if created_at:
            # Strategy 1: Unix timestamp (int or float)
            if isinstance(created_at, (int, float)):
                try:
                    ts        = created_at / 1000 if created_at > 1e10 else created_at
                    parsed_dt = datetime.fromtimestamp(ts, tz=timezone.utc)
                except Exception as exc:
                    log.warning("Unix ts parse failed for @%s value=%r: %s",
                                handle, created_at, exc)

            elif isinstance(created_at, str):
                raw = created_at.strip()

                # Strategy 2: ISO 8601 via fromisoformat (handles Z and +00:00)
                if parsed_dt is None:
                    try:
                        normalized = raw.replace("Z", "+00:00")
                        parsed_dt  = datetime.fromisoformat(normalized)
                        if parsed_dt.tzinfo is None:
                            parsed_dt = parsed_dt.replace(tzinfo=timezone.utc)
                    except ValueError:
                        pass

                # Strategies 3–6: strptime against known format list
                if parsed_dt is None:
                    for fmt in self._DATE_FORMATS:
                        try:
                            parsed_dt = datetime.strptime(raw, fmt)
                            if parsed_dt.tzinfo is None:
                                parsed_dt = parsed_dt.replace(tzinfo=timezone.utc)
                            break
                        except ValueError:
                            continue

                if parsed_dt is None:
                    log.warning(
                        "TWEET DATE PARSE FAILED for @%s — raw value: %r "
                        "Tried: ISO8601, %s. "
                        "Add a new format to ApifyTwitterClient._DATE_FORMATS.",
                        handle, raw, ", ".join(f'"{f}"' for f in self._DATE_FORMATS)
                    )

        if parsed_dt is not None:
            stats.days_since_last_post = (
                datetime.now(timezone.utc) - parsed_dt
            ).total_seconds() / 86400
        else:
            # Default to 999d — if we can't parse the date, the account
            # is likely suspended/deleted, which is itself a death signal.
            stats.days_since_last_post = 999.0
            log.warning("days_since_last_post defaulting to 999d for @%s — "
                        "date field missing or unparseable. Silence metric will trigger.",
                        handle)

        # Tally engagement across all sampled tweets
        for t in originals:
            stats.total_likes    += int(t.get("likeCount") or t.get("favoriteCount") or t.get("likes") or 0)
            stats.total_retweets += int(t.get("retweetCount") or t.get("retweets") or 0)
            stats.total_replies  += int(t.get("replyCount") or t.get("replies") or 0)

        if stats.tweet_count > 0:
            stats.engagement_per_tweet = (
                (stats.total_likes + stats.total_retweets + stats.total_replies)
                / stats.tweet_count
            )

        return stats


# ── Discord Client ────────────────────────────────────────────────────────────

class DiscordClient:
    """Checks Discord server health via the public invite API."""

    def check_invite(self, invite_url: str) -> dict:
        """
        Checks a Discord invite link and returns server health info.

        Returns:
          exists=None   when no invite was provided or the API errored
                        (metric will be skipped)
          exists=False  when the invite is invalid/expired — server likely
                        deleted (2 points)
          exists=True   with member_count for threshold scoring:
                        <100 members = 1 point, ≥100 members = 0 points
        """
        if not invite_url or str(invite_url).strip() in ("", "nan"):
            return {"exists": None, "member_count": 0,
                    "detail": "no_discord_invite – metric skipped"}
        code = str(invite_url).strip().strip("/").split("/")[-1]
        url  = f"https://discord.com/api/v9/invites/{code}?with_counts=true"
        try:
            r = requests.get(url, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
            if r.status_code == 404:
                return {"exists": False, "member_count": 0,
                        "detail": f"invite_invalid_or_expired | code={code}"}
            if r.status_code != 200:
                return {"exists": None, "member_count": 0,
                        "detail": f"discord_api_error_{r.status_code} – metric skipped"}
            data         = r.json()
            member_count = data.get("approximate_member_count", 0)
            online_count = data.get("approximate_presence_count", 0)
            server_name  = data.get("guild", {}).get("name", "unknown")
            return {
                "exists": True, "member_count": member_count,
                "detail": (f"server='{server_name}' | members={member_count:,} "
                           f"| online={online_count:,} | code={code}"),
            }
        except Exception as exc:
            return {"exists": None, "member_count": 0,
                    "detail": f"discord_request_failed – metric skipped ({exc})"}


# ── Stratified metadata sampling ──────────────────────────────────────────────

def _stratified_token_ids(supply: int,
                           sample_size: int = METADATA_SAMPLE_SIZE,
                           bands: int = METADATA_BANDS) -> list:
    """
    Returns a stratified random sample of token IDs from across the full
    supply range, split into `bands` equal segments.

    Stratification prevents sampling bias — checking only low token IDs
    could miss metadata rot in later batches of a collection mint.
    """
    if supply == 0:
        return []
    per_band  = max(1, sample_size // bands)
    band_size = max(1, supply // bands)
    ids = []
    for b in range(bands):
        lo = b * band_size
        hi = min((b + 1) * band_size, supply)
        ids.extend(random.sample(range(lo, hi), min(per_band, hi - lo)))
    return ids


# ── Confidence engine ─────────────────────────────────────────────────────────

def _compute_confidence(metrics, raw_score, rescaled_score,
                        sales_90_count, bid_count, supply,
                        owners_count, max_available) -> dict:
    """
    Produces a multi-dimensional confidence assessment for the score.

    Confidence is LOW when:
      - Few metrics had data (data_completeness)
      - Signals came from only one category (signal_consistency)
      - No recent sales were available to validate market signals (sales_depth)
      - The rescaled score sits close to a verdict boundary (score_margin)

    The overall confidence is the minimum across all individual dimensions,
    so a single weak dimension pulls the whole score to LOW.
    """
    completeness_pct    = max_available / TOTAL_MAX_PTS
    cats_triggered      = len(set(
        METRIC_CATEGORY[m["key"]] for m in metrics
        if m.get("points", 0) > 0 and not _is_skipped(m)
    ))
    metadata_sample_pct = min(METADATA_SAMPLE_SIZE, supply) / supply if supply > 0 else 0
    owner_coverage      = owners_count / supply if supply > 0 else 0
    thresholds          = [11, 7, 4, 0]
    nearest_gap         = min(abs(rescaled_score - t) for t in thresholds)

    f = {
        "confidence_data_completeness":  _rate(completeness_pct,    0.90, 0.70),
        "confidence_signal_consistency": _rate(cats_triggered,       3,    1),
        "confidence_sales_depth":        _rate(sales_90_count,       100,  20),
        "confidence_bid_depth":          _rate(bid_count,            20,   5),
        "confidence_metadata_coverage":  _rate(metadata_sample_pct,  0.10, 0.02),
        "confidence_owner_coverage":     _rate(owner_coverage,       0.50, 0.20),
        "confidence_score_margin":       _rate(nearest_gap,          3,    1),
    }
    level_map = {"HIGH": 2, "MEDIUM": 1, "LOW": 0}
    overall   = min(f.values(), key=lambda x: level_map[x])
    return {
        "confidence_overall": overall,
        **f,
        "conf_detail_completeness_pct":     f"{completeness_pct:.0%}",
        "conf_detail_categories_triggered": cats_triggered,
        "conf_detail_sales_90d":            sales_90_count,
        "conf_detail_active_bids":          bid_count,
        "conf_detail_metadata_sample_pct":  f"{metadata_sample_pct:.1%}",
        "conf_detail_owner_coverage_pct":   f"{owner_coverage:.1%}",
        "conf_detail_score_margin":         nearest_gap,
    }


# ── Scoring Engine ────────────────────────────────────────────────────────────

class NFTDeathScorer:
    """
    Main scoring engine. Orchestrates all API calls and metric evaluations
    for a single NFT collection, returning a complete result dict.

    Usage:
        scorer = NFTDeathScorer()
        result = scorer.score_collection(contract="0x...", name="My Collection", ...)
    """

    def __init__(self):
        self.okx     = OKXClient()
        self.alchemy = AlchemyClient(ALCHEMY_API_KEY)
        self.opensea = OpenSeaClient()
        self.twitter = ApifyTwitterClient()
        self.discord = DiscordClient()

    @staticmethod
    def _bid_price(bid: dict) -> float:
        """Extracts bid price in ETH from an OKX or OpenSea bid dict."""
        return float(bid.get("price", 0) or bid.get("unitPrice", 0) or 0)

    @staticmethod
    def _ask_price(ask: dict) -> float:
        """Extracts ask price in ETH from an OKX or OpenSea listing dict."""
        return float(ask.get("price", 0) or ask.get("unitPrice", 0) or 0)

    # ── Individual metric methods ─────────────────────────────────────────────
    # Each method returns a standard dict:
    #   key       — matches a METRIC_PREFIXES entry
    #   triggered — True if the distress signal fired
    #   points    — points awarded (0 if not triggered or skipped)
    #   detail    — human-readable explanation string for the CSV output

    def _m_liq_volume(self, daily_vols, floor, supply, wash_ratio, trades_30):
        """
        LIQUIDITY: 30-day organic volume < 1% of floor value.

        Organic volume = raw volume minus estimated wash-traded volume.
        Skipped when floor=0 (no active market to measure against).
        Missing floor is already captured by liq_trade_freq and
        fin_active_bids firing independently.
        """
        floor_value = floor * supply
        if floor_value == 0:
            return {"key": "liq_volume_30d_lt1pct_floor_value",
                    "triggered": False, "points": 0,
                    "detail": "no_floor_value – metric skipped"}
        organic_vol = sum(float(t.get("price", 0) or 0) for t in trades_30) * (1.0 - wash_ratio)
        raw_vol_30  = sum(d.get("volume", 0) for d in daily_vols[:30])
        threshold   = floor_value * 0.01
        triggered   = organic_vol < threshold
        detail = (f"organic_30d_vol={organic_vol:.4f}ETH | "
                  f"raw_30d_vol={raw_vol_30:.4f}ETH | "
                  f"wash_ratio={wash_ratio:.1%} | "
                  f"floor_value={floor_value:.4f}ETH | "
                  f"threshold(1%)={threshold:.4f}ETH")
        return {"key": "liq_volume_30d_lt1pct_floor_value",
                "triggered": triggered, "points": 2 if triggered else 0, "detail": detail}

    def _m_liq_trade_freq(self, daily_vols, dune_last_sale_days: float = None):
        """
        LIQUIDITY: No trades for 60 consecutive days.

        Measures the longest zero-trade streak within the live 60-day window.
        Triggers immediately when daily_vols is empty (no trades in 90 days).
        dune_last_sale_days enriches the detail string but does not affect scoring.
        """
        if not daily_vols:
            detail = "no_live_trades_in_90d_window | streak=60+d"
            if dune_last_sale_days is not None and dune_last_sale_days > 60:
                detail = (f"no_live_trades_in_90d_window | "
                          f"dune_last_sale={dune_last_sale_days:.0f}d_ago | "
                          f"streak=60+d_confirmed")
            return {"key": "liq_lt1_trade_per_day_60d",
                    "triggered": True, "points": 2, "detail": detail}

        active_days = {d["day_index"] for d in daily_vols[:60]
                       if d.get("volume", 0) > 0 or d.get("sales_count", 0) > 0}
        max_streak = cur_streak = 0
        for i in range(60):
            if i not in active_days:
                cur_streak += 1
                max_streak = max(max_streak, cur_streak)
            else:
                cur_streak = 0
        triggered = max_streak >= 60
        detail    = (f"longest_zero_trade_streak={max_streak}d | "
                     f"days_with_trades={len(active_days)} | window=60d")
        return {"key": "liq_lt1_trade_per_day_60d",
                "triggered": triggered, "points": 2 if triggered else 0, "detail": detail}

    def _m_fin_active_bid_scarcity(self, supply, bids):
        """
        FINANCIAL: Active bids < 1% of token supply.

        A healthy collection has buyer interest across a meaningful fraction
        of its supply. Zero bids on 50,000 tokens is a clear death signal.
        Skipped when supply is unknown.
        """
        if supply == 0:
            return {"key": "fin_active_bids_lt1pct_supply",
                    "triggered": False, "points": 0,
                    "detail": "no_supply_data – metric skipped"}
        ratio     = len(bids) / supply
        triggered = ratio < 0.01
        detail    = f"active_bids={len(bids)} | supply={supply} | ratio={ratio:.3%}"
        return {"key": "fin_active_bids_lt1pct_supply",
                "triggered": triggered, "points": 2 if triggered else 0, "detail": detail}

    def _m_fin_bid_depth(self, floor, supply, bids):
        """
        FINANCIAL: Total ETH value of top-10 bids < 1% of floor value.

        Measures whether the bid market has meaningful capital behind it,
        not just token count. A collection with 100 bids at 0.0001 ETH
        when floor is 1 ETH has effectively no bid support.
        Skipped when floor=0.
        """
        floor_value = floor * supply
        if floor_value == 0:
            return {"key": "fin_top10_bid_value_lt1pct_floor_value",
                    "triggered": False, "points": 0,
                    "detail": "no_floor_value -- metric skipped"}
        bid_prices = sorted([self._bid_price(b) for b in bids
                              if self._bid_price(b) > 0], reverse=True)
        top10_val  = sum(bid_prices[:10])
        ratio      = top10_val / floor_value
        triggered  = ratio < 0.01
        detail     = (f"top10_bid_value={top10_val:.4f} | "
                      f"floor_value={floor_value:.2f} | ratio={ratio:.4%}")
        return {"key": "fin_top10_bid_value_lt1pct_floor_value",
                "triggered": triggered, "points": 1 if triggered else 0, "detail": detail}

    def _m_soc_twitter_silence(self, tweet_stats, handle: str):
        """
        SOCIAL: No Twitter post in 120+ days.

        Uses days_since_last_post from the Apify scrape.
        Skipped when no Twitter handle is provided or Apify token is absent.
        When Apify returns tweets but no parseable date, defaults to 999d
        (account likely suspended or deleted).
        """
        if tweet_stats is None:
            return {"key": "soc_twitter_silent_120d",
                    "triggered": False, "points": 0,
                    "detail": "no_twitter_handle_or_no_apify_token – metric skipped"}
        days = tweet_stats.days_since_last_post
        if days is None:
            return {"key": "soc_twitter_silent_120d",
                    "triggered": False, "points": 0,
                    "detail": (f"tweet_date_parse_failed – handle=@{handle} "
                               f"– metric skipped (check log for raw date value)")}
        triggered = days >= 120
        detail    = (f"days_since_last_post={days:.1f} | "
                     f"handle=@{handle} | threshold=120d | source=Apify_tweet_scraper")
        return {"key": "soc_twitter_silent_120d",
                "triggered": triggered, "points": 3 if triggered else 0, "detail": detail}

    def _m_soc_discord_dead(self, discord_invite):
        """
        SOCIAL: Discord server deleted or has fewer than 100 members.

        Tiered scoring:
          2 points — invite link is invalid/expired (server likely deleted)
          1 point  — server exists but has <100 members
          0 points — server exists with ≥100 members
        Skipped when no Discord invite is provided.
        """
        result = self.discord.check_invite(discord_invite)
        if result["exists"] is None:
            return {"key": "soc_discord_dead", "triggered": False, "points": 0,
                    "detail": result["detail"]}
        if result["exists"] is False:
            return {"key": "soc_discord_dead", "triggered": True, "points": 2,
                    "detail": result["detail"]}
        if result["member_count"] < 100:
            return {"key": "soc_discord_dead", "triggered": True, "points": 1,
                    "detail": result["detail"]}
        return {"key": "soc_discord_dead", "triggered": False, "points": 0,
                "detail": result["detail"]}

    def _m_soc_engagement_collapse(self, tweet_stats, handle: str):
        """
        SOCIAL: Average engagement per tweet < 5 (likes + RTs + replies).

        Measures whether the community is still interacting with posts,
        even if posting continues. A project tweeting to no response is
        a soft death signal. Requires at least MIN_TWEETS_FOR_ENGAGEMENT
        sampled tweets to avoid noise from single-tweet accounts.
        """
        key = "soc_engagement_collapse"
        if tweet_stats is None:
            return {"key": key, "triggered": False, "points": 0,
                    "detail": "no_twitter_handle_or_no_apify_token – metric skipped"}
        n = tweet_stats.tweet_count
        if n < MIN_TWEETS_FOR_ENGAGEMENT:
            return {"key": key, "triggered": False, "points": 0,
                    "detail": (f"only {n} tweet(s) sampled "
                               f"(min={MIN_TWEETS_FOR_ENGAGEMENT}) – metric skipped")}
        ept       = tweet_stats.engagement_per_tweet
        triggered = ept < ENGAGEMENT_COLLAPSE_THRESHOLD
        detail    = (
            f"tweets_sampled={n} | total_likes={tweet_stats.total_likes} | "
            f"total_retweets={tweet_stats.total_retweets} | "
            f"total_replies={tweet_stats.total_replies} | "
            f"engagement_per_tweet={ept:.2f} | "
            f"threshold={ENGAGEMENT_COLLAPSE_THRESHOLD} | "
            f"handle=@{handle} | source=Apify_tweet_scraper"
        )
        return {"key": key, "triggered": triggered,
                "points": 2 if triggered else 0, "detail": detail}

    def _m_tech_broken_metadata(self, contract, supply):
        """
        TECHNICAL: More than 50% of sampled tokens have broken metadata or images.

        Samples METADATA_SAMPLE_SIZE tokens using stratified random sampling
        across METADATA_BANDS equal segments of the token ID range.

        A token is considered broken when Alchemy returns an error for it,
        or when neither image.originalUrl nor metadata.image is present.

        Skipped when supply is 0 or Alchemy returns no results at all
        (typically a server-side 500 on the contract).
        """
        if supply == 0:
            return {"key": "tech_broken_metadata_gt50pct",
                    "triggered": False, "points": 0,
                    "detail": "no_supply_data – metric skipped"}
        token_ids = _stratified_token_ids(supply)
        nfts      = self.alchemy.token_metadata_batch(contract, token_ids)
        if not nfts:
            return {"key": "tech_broken_metadata_gt50pct",
                    "triggered": False, "points": 0,
                    "detail": "alchemy_metadata_fetch_failed – metric skipped (500 errors on all batches)"}
        broken    = sum(
            1 for n in nfts
            if n.get("error") or
               not (n.get("image", {}).get("originalUrl") or
                    n.get("metadata", {}).get("image", ""))
        )
        pct       = broken / len(nfts)
        triggered = pct > 0.50
        detail    = (f"sampled={len(nfts)} ({METADATA_BANDS} stratified bands) | "
                     f"broken={broken} | broken_pct={pct:.1%} | supply={supply}")
        return {"key": "tech_broken_metadata_gt50pct",
                "triggered": triggered, "points": 3 if triggered else 0, "detail": detail}

    def _m_inv_listing_pct(self, supply, asks):
        """
        INVENTORY: More than 20% of supply is listed for sale.

        High listing rates indicate holders are trying to exit — a classic
        distress signal. Skipped when supply is unknown.
        """
        if supply == 0:
            return {"key": "inv_gt20pct_supply_listed",
                    "triggered": False, "points": 0,
                    "detail": "no_supply_data – metric skipped"}
        ratio     = len(asks) / supply
        triggered = ratio > 0.20
        detail    = f"listed={len(asks)} | supply={supply} | ratio={ratio:.1%}"
        return {"key": "inv_gt20pct_supply_listed",
                "triggered": triggered, "points": 1 if triggered else 0, "detail": detail}

    def _m_own_concentration(self, owners):
        """
        OWNERSHIP: Top-10 wallets hold more than 50% of token supply.

        Extreme concentration signals that the collection is effectively
        controlled by a handful of wallets, suppressing organic market activity.

        Uses Alchemy v3 tokenBalances field ('balance', not 'tokenCount').
        Falls back to skipping cleanly when balance data is unavailable.
        """
        if not owners:
            return {"key": "own_top10_wallets_gt50pct_supply",
                    "triggered": False, "points": 0,
                    "detail": "no_ownership_data – metric skipped"}

        def bal(o):
            tbs = o.get("tokenBalances") or []
            return sum(int(tb.get("balance") or tb.get("tokenCount") or 0) for tb in tbs)

        total = sum(bal(o) for o in owners)
        if total == 0:
            return {"key": "own_top10_wallets_gt50pct_supply",
                    "triggered": False, "points": 0,
                    "detail": (f"balance_field_empty – fallback to owner_count | "
                               f"unique_owners={len(owners)} | "
                               f"note=check_Alchemy_tokenBalances_field_names")}

        top10     = sum(bal(o) for o in sorted(owners, key=bal, reverse=True)[:10])
        ratio     = top10 / total if total else 0
        triggered = ratio > 0.50
        detail    = (f"top10_tokens={top10} | total_tokens={total} | "
                     f"ratio={ratio:.1%} | unique_owners={len(owners)}")
        return {"key": "own_top10_wallets_gt50pct_supply",
                "triggered": triggered, "points": 1 if triggered else 0, "detail": detail}

    # ── Main scoring entry point ──────────────────────────────────────────────

    def score_collection(self, contract: str, name: str = "",
                         twitter_handle: str = "",
                         discord_invite: str = "",
                         opensea_slug: str = "",
                         opensea_link: str = "",
                         dune_token_count: int = 0,
                         dune_last_sale_time: str = "") -> dict:
        """
        Scores a single NFT collection across all active metrics.

        Data flow:
          1. Parse dune_last_sale_time for liq_trade_freq detail enrichment only
          2. Fetch collection details from OKX (5-strategy slug resolution)
          3. Fetch market data from OKX (trades, bids, listings)
          4. If OKX has no market data, fall back to OpenSea
          5. Fetch ownership data from Alchemy (paginated)
          6. Fetch Twitter stats from Apify (single call for two metrics)
          7. Run all 10 metrics and compute raw score
          8. Rescale raw score to RESCALE_NORM and apply verdict thresholds

        Returns a dict with contract, name, scores, verdict, confidence,
        and per-metric details.
        """
        log.info("-- Scoring: %s  (%s)", name or contract, contract)
        now = datetime.now(timezone.utc)

        # Parse Dune last-sale date for detail enrichment (no scoring impact)
        dune_last_sale_days: float = None
        if dune_last_sale_time and str(dune_last_sale_time).strip() not in ("", "nan", "None"):
            try:
                raw = str(dune_last_sale_time).replace(" UTC", "").strip()
                raw = raw.split(".")[0].replace(" ", "T") + "+00:00"
                dune_last_sale_days = (now - datetime.fromisoformat(raw)).total_seconds() / 86400
                log.info("   dune: last_sale=%.0fd ago", dune_last_sale_days)
            except Exception as exc:
                log.warning("Could not parse dune_last_sale_time %r: %s",
                            dune_last_sale_time, exc)

        # Fetch OKX collection details
        okx_details = self.okx.collection_details(
            contract, slug=opensea_slug,
            opensea_link=opensea_link, collection_name=name,
        )

        if not okx_details and not dune_token_count:
            log.info("    SKIP -- no OKX data and no token count")
            return {
                "contract": contract, "name": name,
                "image_url": "", "floor": 0, "floor_currency": "",
                "supply": 0, "timestamp": now.isoformat(),
                "raw_score": 0, "skipped_pts": TOTAL_MAX_PTS,
                "max_available": 0, "rescaled_score": 0,
                "verdict": "SKIPPED -- not a tradeable NFT collection",
                "confidence": {"confidence_overall": "LOW"},
                "metrics": [],
            }

        image_url  = self.okx.collection_image(okx_details)
        supply     = self.okx.supply(okx_details) or dune_token_count
        floor_sym  = okx_details.get("floorPriceSymbol", "ETH")
        market_src = "OKX"

        # Fetch OKX market data
        trades_90  = self.okx.trade_history(contract, days=90)
        trades_30  = [t for t in trades_90 if _sale_age_days(t) <= 30]
        asks       = self.okx.active_listings(contract)
        bids       = self.okx.active_bids(contract)
        daily_vols = self.okx.daily_volume_proxy(trades_90)

        # Fall back to OpenSea if OKX has no market data at all
        okx_floor_direct = 0.0
        try:
            okx_floor_direct = float(okx_details.get("floorPrice") or 0)
        except Exception:
            pass

        if okx_floor_direct == 0 and not trades_90 and not asks:
            log.info("   OKX has no market data -- trying OpenSea fallback")
            os_slug = self.opensea.resolve_slug(contract)
            if os_slug:
                os_floor  = self.opensea.floor_price_eth(os_slug)
                os_asks   = self.opensea.active_listings(os_slug)
                os_bids   = self.opensea.active_offers(os_slug)
                os_trades = self.opensea.trade_events(os_slug, days=90)
                if os_floor > 0 or os_asks or os_trades:
                    trades_90   = os_trades
                    trades_30   = [t for t in os_trades if _sale_age_days(t) <= 30]
                    asks        = os_asks
                    bids        = os_bids
                    daily_vols  = self.okx.daily_volume_proxy(os_trades)
                    floor_sym   = "ETH"
                    market_src  = "OpenSea"
                    okx_details = dict(okx_details)
                    okx_details["floorPrice"] = os_floor
                    log.info("   OpenSea active: floor=%.6f | listings=%d | "
                             "offers=%d | trades_90d=%d",
                             os_floor, len(os_asks), len(os_bids), len(os_trades))
                else:
                    log.info("   OpenSea also has no market data for %s", contract[:12])
            else:
                log.info("   OpenSea slug not found for %s", contract[:12])

        # Resolve floor using the three-tier fallback chain
        floor = self.okx.floor_price_eth(okx_details, asks=asks, trades=trades_90)

        # Derive wash ratio for volume metric (wash detection needs active trades)
        wash_ratio = 0.0
        if trades_30:
            by_token    = defaultdict(list)
            pair_counts = defaultdict(int)
            for s in trades_30:
                tid = s.get("nftId") or s.get("tokenId")
                ts  = int(s.get("tradeTime", 0) or 0)
                if ts > 1e10: ts = ts // 1000
                if tid and ts: by_token[tid].append(ts)
                buyer  = (s.get("buyer") or s.get("buyerAddress", "")).lower()
                seller = (s.get("seller") or s.get("sellerAddress", "")).lower()
                if buyer and seller and buyer != seller:
                    pair_counts[tuple(sorted([buyer, seller]))] += 1
            flip_txns = sum(
                1 for times in by_token.values()
                for i in range(1, len(sorted(times)))
                if sorted(times)[i] - sorted(times)[i-1] < 3600
            )
            pair_wash = sum(c for c in pair_counts.values() if c > 2) * 2
            wash      = flip_txns + pair_wash
            wash_ratio = min(wash / len(trades_30), 1.0)

        # Fetch Alchemy ownership data (paginated)
        owners = self.alchemy.owners(contract)

        # Fetch Twitter data (single Apify call feeds two metrics)
        tweet_stats = self.twitter.fetch_tweet_stats(twitter_handle)

        log.info("   src=%s | floor=%.4f %s | supply=%d | 90d_trades=%d | "
                 "bids=%d | asks=%d | owners=%d",
                 market_src, floor, floor_sym, supply, len(trades_90),
                 len(bids), len(asks), len(owners))

        if tweet_stats:
            log.info("   twitter: days_since_post=%s | tweets=%d | "
                     "likes=%d | RTs=%d | replies=%d | eng/tweet=%.2f",
                     f"{tweet_stats.days_since_last_post:.1f}"
                     if tweet_stats.days_since_last_post is not None else "None",
                     tweet_stats.tweet_count, tweet_stats.total_likes,
                     tweet_stats.total_retweets, tweet_stats.total_replies,
                     tweet_stats.engagement_per_tweet)

        # Evaluate all 10 active metrics
        metrics = [
            self._m_liq_volume(daily_vols, floor, supply, wash_ratio, trades_30),
            self._m_liq_trade_freq(daily_vols, dune_last_sale_days=dune_last_sale_days),
            self._m_fin_active_bid_scarcity(supply, bids),
            self._m_fin_bid_depth(floor, supply, bids),
            self._m_soc_twitter_silence(tweet_stats, twitter_handle),
            self._m_soc_discord_dead(discord_invite),
            self._m_soc_engagement_collapse(tweet_stats, twitter_handle),
            self._m_tech_broken_metadata(contract, supply),
            self._m_inv_listing_pct(supply, asks),
            self._m_own_concentration(owners),
        ]

        skipped_pts       = sum(METRIC_MAX_PTS[m["key"]] for m in metrics if _is_skipped(m))
        max_available     = TOTAL_MAX_PTS - skipped_pts
        raw_score         = sum(m["points"] for m in metrics)
        rescaled          = _rescale(raw_score, max_available)
        metrics_with_data = sum(1 for m in metrics if not _is_skipped(m))
        verdict           = _verdict(rescaled, metrics_with_data=metrics_with_data)

        confidence = _compute_confidence(
            metrics=metrics, raw_score=raw_score, rescaled_score=rescaled,
            sales_90_count=len(trades_90), bid_count=len(bids),
            supply=supply, owners_count=len(owners), max_available=max_available,
        )

        log.info("   RAW=%d | MAX_AVAIL=%d | RESCALED=%d | "
                 "METRICS_W_DATA=%d/%d | VERDICT=%s | CONF=%s",
                 raw_score, max_available, rescaled,
                 metrics_with_data, len(metrics),
                 verdict, confidence["confidence_overall"])

        return {
            "contract":       contract,
            "name":           name,
            "image_url":      image_url,
            "floor":          floor,
            "floor_currency": floor_sym,
            "market_source":  market_src,
            "supply":         supply,
            "wash_ratio":     f"{wash_ratio:.1%}",
            "timestamp":      now.isoformat(),
            "raw_score":      raw_score,
            "skipped_pts":    skipped_pts,
            "max_available":  max_available,
            "rescaled_score": rescaled,
            "verdict":        verdict,
            "confidence":     confidence,
            "metrics":        metrics,
        }


# ── CSV / JSON output helpers ─────────────────────────────────────────────────

CONFIDENCE_COLS = [
    "confidence_overall", "confidence_data_completeness",
    "confidence_signal_consistency", "confidence_sales_depth",
    "confidence_bid_depth", "confidence_metadata_coverage",
    "confidence_owner_coverage", "confidence_score_margin",
    "conf_detail_completeness_pct", "conf_detail_categories_triggered",
    "conf_detail_sales_90d", "conf_detail_active_bids",
    "conf_detail_metadata_sample_pct", "conf_detail_owner_coverage_pct",
    "conf_detail_score_margin",
]

FIXED_COLS = [
    "contract", "name", "image_url",
    "opensea_link", "standard", "first_mint_time",
    "dune_token_count", "dune_total_sales", "dune_last_sale_time",
    "dune_volume_usd_all_time", "twitter_handle", "discord_invite",
    "floor", "floor_currency", "market_source", "supply", "wash_ratio",
    "timestamp", "raw_score", "skipped_pts", "max_available",
    "rescaled_score", "verdict",
]


def result_to_row(result: dict, dune_row: dict) -> dict:
    """
    Flattens a score_collection() result dict into a flat CSV row.
    Merges in original input fields from the Dune CSV row so the output
    is self-contained for downstream analysis.
    """
    row = {
        "contract":               result["contract"],
        "name":                   result.get("name", ""),
        "image_url":              result.get("image_url", ""),
        "opensea_link":           dune_row.get("opensea_link", ""),
        "standard":               dune_row.get("standard", ""),
        "first_mint_time":        dune_row.get("first_mint_time", ""),
        "dune_token_count":       dune_row.get("token_count", ""),
        "dune_total_sales":       dune_row.get("total_sales", ""),
        "dune_last_sale_time":    dune_row.get("last_sale_time", ""),
        "dune_volume_usd_all_time": dune_row.get("volume_usd_all_time", ""),
        "twitter_handle":         dune_row.get("twitter_handle", ""),
        "discord_invite":         dune_row.get("discord_invite", ""),
        "floor":                  result.get("floor", ""),
        "floor_currency":         result.get("floor_currency", ""),
        "market_source":          result.get("market_source", "OKX"),
        "supply":                 result.get("supply", ""),
        "wash_ratio":             result.get("wash_ratio", ""),
        "timestamp":              result.get("timestamp", ""),
        "raw_score":              result.get("raw_score", ""),
        "skipped_pts":            result.get("skipped_pts", ""),
        "max_available":          result.get("max_available", ""),
        "rescaled_score":         result.get("rescaled_score", ""),
        "verdict":                result.get("verdict", ""),
    }
    for col in CONFIDENCE_COLS:
        row[col] = result.get("confidence", {}).get(col, "")
    metric_map = {m["key"]: m for m in result.get("metrics", [])}
    for prefix in METRIC_PREFIXES:
        m = metric_map.get(prefix, {})
        row[f"{prefix}_label"]     = METRIC_LABELS.get(prefix, "")
        row[f"{prefix}_max_pts"]   = METRIC_MAX_PTS.get(prefix, "")
        row[f"{prefix}_category"]  = METRIC_CATEGORY.get(prefix, "")
        row[f"{prefix}_triggered"] = "YES" if m.get("triggered") else ("NO" if m else "")
        row[f"{prefix}_skipped"]   = "YES" if _is_skipped(m) else "NO"
        row[f"{prefix}_points"]    = m.get("points", "")
        row[f"{prefix}_detail"]    = m.get("detail", "")
    return row


def error_row(contract: str, dune_row: dict, error: str) -> dict:
    """
    Produces a CSV row for a collection that failed to score due to an
    unexpected exception, preserving all input fields for debugging.
    """
    row = {
        "contract": contract, "name": dune_row.get("name", ""),
        "image_url": "", "opensea_link": dune_row.get("opensea_link", ""),
        "standard": dune_row.get("standard", ""),
        "first_mint_time": dune_row.get("first_mint_time", ""),
        "dune_token_count": dune_row.get("token_count", ""),
        "dune_total_sales": dune_row.get("total_sales", ""),
        "dune_last_sale_time": dune_row.get("last_sale_time", ""),
        "dune_volume_usd_all_time": dune_row.get("volume_usd_all_time", ""),
        "twitter_handle": dune_row.get("twitter_handle", ""),
        "discord_invite": dune_row.get("discord_invite", ""),
        "floor": "", "floor_currency": "", "supply": "", "wash_ratio": "",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "raw_score": "ERROR", "skipped_pts": "",
        "max_available": "", "rescaled_score": "ERROR",
        "verdict": f"ERROR: {error}",
    }
    for col in CONFIDENCE_COLS:
        row[col] = ""
    for prefix in METRIC_PREFIXES:
        row[f"{prefix}_label"]     = METRIC_LABELS.get(prefix, "")
        row[f"{prefix}_max_pts"]   = METRIC_MAX_PTS.get(prefix, "")
        row[f"{prefix}_category"]  = METRIC_CATEGORY.get(prefix, "")
        row[f"{prefix}_triggered"] = ""
        row[f"{prefix}_skipped"]   = ""
        row[f"{prefix}_points"]    = ""
        row[f"{prefix}_detail"]    = "collection_error"
    return row


# ── CLI entry point ───────────────────────────────────────────────────────────

def main():
    """
    Reads a CSV of NFT collections, scores each one, and writes results
    to both a flat CSV and a full JSON file.

    Input CSV expected columns:
      contract_address, name, twitter_handle, discord_invite,
      opensea_slug, opensea_link, last_sale_time, token_count

    Output:
      nft_death_scores.csv  — flat CSV, one row per collection
      nft_death_scores.json — full nested JSON with all metric details
    """
    parser = argparse.ArgumentParser(description="NFT Death Score Analyzer v12")
    parser.add_argument("--input",  default="input_socials.csv") # INPUT CSV = entire collection of nfts to score
    parser.add_argument("--output", default="nft_death_scores.csv")
    parser.add_argument("--json",   default="nft_death_scores.json")
    args, _ = parser.parse_known_args()

    # Warn about missing optional API keys
    missing = [k for k, v in {
        "ALCHEMY_API_KEY":    ALCHEMY_API_KEY,
        "OKX_API_KEY":        OKX_API_KEY,
        "OKX_API_SECRET":     OKX_API_SECRET,
        "OKX_API_PASSPHRASE": OKX_API_PASSPHRASE,
    }.items() if not v]
    if missing:
        log.warning("Missing required keys (metrics will be skipped): %s", missing)
    if not APIFY_API_TOKEN:
        log.warning("APIFY_API_TOKEN not set – Twitter metrics skipped")
    if not OPENSEA_API_KEY:
        log.warning("OPENSEA_API_KEY not set – OpenSea fallback disabled")

    scorer = NFTDeathScorer()
    rows, full_results = [], []

    with open(args.input, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        reader.fieldnames = [name.strip().lower() for name in reader.fieldnames]
        collections = list(reader)

    log.info("Loaded %d collections from %s", len(collections), args.input)

    for col in tqdm(collections, desc="Scoring"):
        contract = str(col.get("contract_address") or "").strip()
        name     = str(col.get("name") or "").strip()
        if not contract:
            log.warning("Skipping row with no contract: %s", name)
            continue
        try:
            result = scorer.score_collection(
                contract            = contract,
                name                = name,
                twitter_handle      = str(col.get("twitter_handle") or "").strip(),
                discord_invite      = str(col.get("discord_invite") or "").strip(),
                opensea_slug        = str(col.get("opensea_slug") or "").strip(),
                opensea_link        = str(col.get("opensea_link") or "").strip(),
                dune_token_count    = int(col.get("token_count", 0) or 0),
                dune_last_sale_time = str(col.get("last_sale_time") or "").strip(),
            )
            full_results.append(result)
            rows.append(result_to_row(result, col))
        except Exception as exc:
            log.error("Failed to score %s (%s): %s", name, contract, exc)
            rows.append(error_row(contract, col, str(exc)))
        time.sleep(0.5)

    # Write CSV output
    if rows:
        df = pd.DataFrame(rows)
        metric_cols = []
        for p in METRIC_PREFIXES:
            metric_cols += [f"{p}_label", f"{p}_category", f"{p}_max_pts",
                            f"{p}_triggered", f"{p}_skipped",
                            f"{p}_points",    f"{p}_detail"]
        ordered = [c for c in FIXED_COLS + CONFIDENCE_COLS + metric_cols
                   if c in df.columns]
        df[ordered].to_csv(args.output, index=False)
        log.info("CSV → %s  (%d rows, %d columns)", args.output, len(df), len(ordered))

    # Write JSON output
    with open(args.json, "w") as f:
        json.dump(full_results, f, indent=2, default=str)
    log.info("JSON → %s", args.json)

    # Console summary table
    print("\n" + "=" * 90)
    print(f"{'Name':<28} {'Raw':>4} {'Max':>4} {'Score':>6}  "
          f"{'Verdict':<22}  {'Conf':<7}  Wash%")
    print("=" * 90)
    for row in rows:
        name    = str(row.get("name", row.get("contract", "")))[:27]
        print(f"{name:<28} {str(row.get('raw_score','')):>4} "
              f"{str(row.get('max_available','')):>4} "
              f"{str(row.get('rescaled_score','ERR')):>6}  "
              f"{str(row.get('verdict',''))[:21]:<22}  "
              f"{str(row.get('confidence_overall',''))::<7}  "
              f"{str(row.get('wash_ratio',''))}")
    print("=" * 90)

    verdicts = [r.get("verdict", "") for r in rows
                if "ERROR" not in str(r.get("verdict", ""))]
    di_count = sum(1 for v in verdicts if v.startswith("Data Insufficient"))
    print(f"\n  DEAD:                 {verdicts.count('DEAD'):>4}")
    print(f"  Institutional Decay:  {verdicts.count('Institutional Decay'):>4}")
    print(f"  Stressed/Declining:   {verdicts.count('Stressed / Declining'):>4}")
    print(f"  Alive or Recoverable: {verdicts.count('Alive or Recoverable'):>4}")
    print(f"  Data Insufficient:    {di_count:>4}")
    print(f"  Errors:               "
          f"{sum(1 for r in rows if 'ERROR' in str(r.get('verdict', ''))):>4}")
    print(f"\n  Output: {args.output}  |  {args.json}\n")


if __name__ == "__main__":
    main()